# Generated by Django 3.0.8 on 2021-08-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210724_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id_marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.Marca'),
        ),
        migrations.AlterField(
            model_name='articulo_categoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articulo_categoria',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.Categoria'),
        ),
        migrations.AlterField(
            model_name='pedido_articulo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido_articulo',
            name='id_articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.Articulo'),
        ),
        migrations.AlterField(
            model_name='pedido_articulo',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.Pedido'),
        ),
    ]
